### ISSUE TITLE
eslint-config-prettier is in dependencies, not devDependencies

### ISSUE THREAD

**Issue by themaxdavitt** [node-loader/node-loader-core#5]
It looks like [`eslint-config-prettier`](https://www.npmjs.com/package/eslint-config-prettier) is in the [`dependencies` section of `package.json`](https://github.com/node-loader/node-loader-core/blob/0adf95ce577e74a28d5643c753bff176cd658c24/package.json#L45) - judging by where all the other `eslint` packages are, I'm guessing it should be in `devDependencies`.

**Comment by joeldenning** [comment]
Thanks for reporting this, I've fixed it in #6

**Comment by joeldenning** [comment]
Fix released in https://github.com/node-loader/node-loader-core/releases/tag/v1.0.5
