### ISSUE TITLE
Update to latest load hooks API

### ISSUE THREAD

**Issue by hpx7** [node-loader/node-loader-core#7]
This module doesn't seem to work in 16.12, see https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.12.0

**Comment by hpx7** [comment]
Hey @joeldenning just wanted to check if you think you'll have time to look into this soon? No worries if not

**Comment by joeldenning** [comment]
For projects like this I usually just do them when the inspiration strikes. I am quite busy and fairly burned out so I don't do as much open source as I used to. Could be this week or could be in a couple months

**Comment by joeldenning** [comment]
Node 16.12 is supported in 2.0.0. See https://github.com/node-loader/node-loader-core/releases/tag/v2.0.0.

I plan on working on node-loader/import-maps and node-loader/http next. Let me know if you are using other loaders and I'll try to prioritize those, too

**Comment by joeldenning** [comment]
node-loader/http@2 now supports node 16.12: https://github.com/node-loader/node-loader-http/releases/tag/v2.0.0

**Comment by joeldenning** [comment]
node-loader/import-maps requires no changes since it only uses the resolve hook

**Comment by joeldenning** [comment]
node-loader/postcss@2 now supports Node 16.12. See https://github.com/node-loader/node-loader-postcss/releases/tag/v2.0.0

**Comment by joeldenning** [comment]
node-loader/babel@2 now supports Node 16.12. See https://github.com/node-loader/node-loader-babel/releases/tag/v2.0.0

**Comment by joeldenning** [comment]
That's all of them! So everything should now be compatible with node 16.12

**Comment by hpx7** [comment]
I upgraded and it works great, thanks!
